version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: gobackend
    ports:
      - "3333:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: admin12345
      DB_NAME: gobackend
      DB_HOST: db
    command: ["/wait-for-it.sh", "db:3306", "--", "./server"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
