name: Build exercise10
on:
  push:
    branches:
      - master
      - exercise10-cloud

permissions:
  contents: read

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Build and push frontend
        working-directory: exercise10-cloud/frontend
        run: |
          docker build -t $DOCKER_USER/uj-app-frontend .
          docker push $DOCKER_USER/uj-app-frontend

      - name: Build and push backend
        working-directory: exercise10-cloud/backend
        run: |
          docker build -t $DOCKER_USER/uj-app-backend .
          docker push $DOCKER_USER/uj-app-backend

  deploy_backend:
    permissions:
      contents: none
    needs: build_and_push
    runs-on: ubuntu-latest
    environment:
      name: 'Production backend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: uj-app-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: ${{ env.DOCKER_USER }}/uj-app-backend:latest

  deploy_frontend:
    permissions:
      contents: none
    needs: build_and_push
    runs-on: ubuntu-latest
    environment:
      name: 'Production frontend'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: uj-app-frontend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: ${{ env.DOCKER_USER }}/uj-app-frontend:latest